[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "AboutMe/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/w40141"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/wxy40"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
# [[social]]
#   name = "rss"
#   weight = 4
#   url = "index.xml"
[[social]]
  name = "spotify"
  weight = 5
  url = "https://open.spotify.com/show/32szHs4IbCOb4GWW8cduKh?si=Lv7y3zqJSJCBH7IkEGP9eA"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
